import math
from os.path import expanduser

# Add-on Configuration

ADDON_SHORT_NAME = "vlips"
ADDON_VERSION = "2.2.0"

# Operators Names

SETUP_BEACON_OPERATOR_NAME = f"mesh.{ADDON_SHORT_NAME}_setup_beacon"
SETUP_CAMERA_OPERATOR_NAME = f"mesh.{ADDON_SHORT_NAME}_setup_camera"
EMPTY_SCENE_OPERATOR_NAME = f"mesh.{ADDON_SHORT_NAME}_empty_scene"
CREATE_SCENE_OPERATOR_NAME = f"mesh.{ADDON_SHORT_NAME}_create_create"
LOAD_SETTINGS_OPERATOR_NAME = f"mesh.{ADDON_SHORT_NAME}_load_settings"
SAVE_SETTINGS_OPERATOR_NAME = f"mesh.{ADDON_SHORT_NAME}_save_settings"
SETUP_CAMERA_MOVEMENT_OPERATOR_NAME = f"mesh.{ADDON_SHORT_NAME}_setup_camera_movement"
RENDER_SCENE_OPERATOR_NAME = f"mesh.{ADDON_SHORT_NAME}_render_scene"
RENDER_CAMERA_MOVEMENT_OPERATOR_NAME = f"mesh.{ADDON_SHORT_NAME}_render_camera_movement"
RENDER_CAMERA_FOV_CORNERS_NAME = f"mesh.{ADDON_SHORT_NAME}_render_camera_fov_corners"
SETUP_ROOM_OPERATOR_NAME = f"mesh.{ADDON_SHORT_NAME}_setup_room"
SETUP_SCENE_OPERATOR_NAME = f"mesh.{ADDON_SHORT_NAME}_setup_scene"
SETUP_TEXTS_OPERATOR_NAME = f"mesh.{ADDON_SHORT_NAME}_setup_texts"
SETUP_CAMERA_MOVEMENT_DISTANCE_OPERATOR_NAME = f"mesh.{ADDON_SHORT_NAME}_setup_camera_movement_distance"
SETUP_CAMERA_MOVEMENT_ROTATION_X_ANGLE_OPERATOR_NAME = \
    f"mesh.{ADDON_SHORT_NAME}_setup_camera_movement_rotation_x_angle"
SETUP_CAMERA_MOVEMENT_ROTATION_Z_ANGLE_OPERATOR_NAME = \
    f"mesh.{ADDON_SHORT_NAME}_setup_camera_movement_rotation_z_angle"

# Scene Operator Constants

DEFAULT_TILE_SIDE = 50  # millimeters
MIN_TILE_SIDE = 10
MAX_TILE_SIDE = 1000

DEFAULT_FLOOR_SIDE_TILES = 32  # tiles
MIN_FLOOR_SIDE_TILES = 1
MAX_FLOOR_SIDE_TILES = 100

DISTANCE_STEP = 100  # millimeters

# Room Operator Constants

DEFAULT_ROOM_NAME = "Room"
ROOM_STEP = 100  # millimeters

DEFAULT_ROOM_DEPTH = 4000  # millimeters
MIN_ROOM_DEPTH = 1000
MAX_ROOM_DEPTH = 10000

DEFAULT_ROOM_WIDTH = 6000  # millimeters
MIN_ROOM_WIDTH = 1000
MAX_ROOM_WIDTH = 10000

DEFAULT_ROOM_HEIGHT = 2000  # millimeters
MIN_ROOM_HEIGHT = 1000
MAX_ROOM_HEIGHT = 4000

DEFAULT_ROOM_THICKNESS = 50  # millimeters
MIN_ROOM_THICKNESS = 0
MAX_ROOM_THICKNESS = 1000

# Beacon Operator Constants

DEFAULT_BEACON_NAME = "Beacon"

DEFAULT_BEACON_WIDTH = 174  # millimeters
MIN_BEACON_WIDTH = 0
MAX_BEACON_WIDTH = 500

DEFAULT_BEACON_HEIGHT = 174  # millimeters
MIN_BEACON_HEIGHT = 0
MAX_BEACON_HEIGHT = 500

DEFAULT_BEACON_ROTATION = (0.0, 0.0, 0.0)

# Camera constants

DEFAULT_CAMERA_NAME = "Camera"

DEFAULT_CAMERA_MAKE = "Xiaomi"

DEFAULT_CAMERA_MODEL = "MI 8"

CAMERA_SOFTWARE = "CAMERA_SOFTWARE"
DEFAULT_CAMERA_SOFTWARE = ""

DEFAULT_CAMERA_ORIENTATION = "portrait"

DEFAULT_CAMERA_FACING = "front"

FRONT_CAMERA_RESOLUTION_WIDTH = 5184  # pixels
FRONT_CAMERA_RESOLUTION_HEIGHT = 3880  # pixels
FRONT_CAMERA_FOCAL_LENGTH = 3.52  # millimetres
FRONT_CAMERA_PIXEL_SIZE = 0.0009  # millimetres

BACK_CAMERA_RESOLUTION_WIDTH = 4032  # pixels
BACK_CAMERA_RESOLUTION_HEIGHT = 3024  # pixels
BACK_CAMERA_FOCAL_LENGTH = 4.216  # millimetres
BACK_CAMERA_PIXEL_SIZE = 0.0014  # millimetres

DEFAULT_CAMERA_RESOLUTION_WIDTH = FRONT_CAMERA_RESOLUTION_WIDTH  # pixels
MIN_CAMERA_RESOLUTION_WIDTH = 1024
MAX_CAMERA_RESOLUTION_WIDTH = 10240

DEFAULT_CAMERA_RESOLUTION_HEIGHT = FRONT_CAMERA_RESOLUTION_HEIGHT  # pixels
MIN_CAMERA_RESOLUTION_HEIGHT = 768
MAX_CAMERA_RESOLUTION_HEIGHT = 7680

DEFAULT_CAMERA_FOCAL_LENGTH = FRONT_CAMERA_FOCAL_LENGTH  # millimetres
MIN_CAMERA_FOCAL_LENGTH = 0
MAX_CAMERA_FOCAL_LENGTH = 10

DEFAULT_CAMERA_PIXEL_SIZE = FRONT_CAMERA_PIXEL_SIZE  # millimetres
MIN_CAMERA_PIXEL_SIZE = 0
MAX_CAMERA_PIXEL_SIZE = 0.01

DEFAULT_CAMERA_BEACON_DISTANCE = 1000  # millimeters
MIN_CAMERA_BEACON_DISTANCE = 0
MAX_CAMERA_BEACON_DISTANCE = DEFAULT_ROOM_HEIGHT

DEFAULT_CAMERA_ROTATION = (180.0, 0.0, 180.0)  # degrees

DEFAULT_CAMERA_ROTATION_X_ANGLE = 0  # degrees
MIN_CAMERA_ROTATION_X_ANGLE = -90
MAX_CAMERA_ROTATION_X_ANGLE = 90

DEFAULT_CAMERA_ROTATION_Z_ANGLE = 0  # degrees
MIN_CAMERA_ROTATION_Z_ANGLE = -180
MAX_CAMERA_ROTATION_Z_ANGLE = 180

DEFAULT_CAMERA_VERTICAL_ROTATION_ANGLE = 0.0  # degrees
MIN_CAMERA_VERTICAL_ROTATION_ANGLE = 0.0
MAX_CAMERA_VERTICAL_ROTATION_ANGLE = 90.0

DEFAULT_CAMERA_LOCATION = (
    DEFAULT_CAMERA_BEACON_DISTANCE * math.cos(math.radians(DEFAULT_CAMERA_ROTATION_X_ANGLE)),
    DEFAULT_ROOM_WIDTH / 2 +
    DEFAULT_CAMERA_BEACON_DISTANCE * math.sin(math.radians(DEFAULT_CAMERA_ROTATION_X_ANGLE)),
    DEFAULT_ROOM_HEIGHT / 2
)

CAMERA_FOV_SUFFIX = " FOV"
CAMERA_FOV_COLLECTION_NAME = f"Camera{CAMERA_FOV_SUFFIX}"
CAMERA_FOV_FULL_NAME = "1. Full"
CAMERA_FOV_BEACON_NAME = "2. Beacon"
CAMERA_FOV_TILES_NAME = "3. Tiles"
CAMERA_FOV_EVEN_TILES_NAME = "4. Even Tiles"

CAMERA_FOV_FULL_COLOR = (.1, .1, .1, .5)
CAMERA_FOV_BEACON_COLOR = (.2, .2, .2, .6)
CAMERA_FOV_TILES_COLOR = (.3, .3, .3, .7)
CAMERA_FOV_EVEN_TILES_COLOR = (.4, .4, .4, .8)

DEFAULT_SHOW_CAMERA_FOV = False
DEFAULT_CAMERA_FOV_LOCATION = [0, 0, 0]
DEFAULT_CAMERA_FOV_ROTATION = [0, 0, 0]

# Texts constants

DEFAULT_FONT_SIZE = 200  # millimeters
MIN_FONT_SIZE = 0
MAX_FONT_SIZE = 1000

TEXT_COLLECTION_NAME = "Text"

TEXT_DISTANCE_KEY = "Distance"
TEXT_HEIGHT_KEY = "Height"
TEXT_HORIZONTAL_ROTATION_KEY = "Horizontal Rotation"
TEXT_VERTICAL_ROTATION_KEY = "Vertical Rotation"
TEXT_X_KEY = "X"
TEXT_Y_KEY = "Y"
TEXT_GRID_KEY = "Grid"
TEXT_ROTATION_KEY = "Rotation"
TEXT_ROTATION_X_KEY = "X Angle"
TEXT_ROTATION_Z_KEY = "Z Angle"
TEXT_ROTATION_X = "X"
TEXT_ROTATION_Z = "Z"

# Movement constants

DEFAULT_CAMERA_MOVEMENT_FOV_SCAN_ENABLED = True
DEFAULT_CAMERA_MOVEMENT_BEACON_DISTANCE_ENABLED = False
DEFAULT_CAMERA_MOVEMENT_ROTATION_X_ANGLE_ENABLED = False
DEFAULT_CAMERA_MOVEMENT_ROTATION_Z_ANGLE_ENABLED = False

DEFAULT_CAMERA_DISTANCE_STEP = 100  # millimeters
MIN_CAMERA_DISTANCE_STEP = 10
MAX_CAMERA_DISTANCE_STEP = 1000

DEFAULT_CAMERA_DISTANCE_START = 300  # millimeters
MIN_CAMERA_DISTANCE_START = 0
MAX_CAMERA_DISTANCE_START = DEFAULT_ROOM_HEIGHT

DEFAULT_CAMERA_DISTANCE_END = DEFAULT_ROOM_HEIGHT  # millimeters
MIN_CAMERA_DISTANCE_END = 0
MAX_CAMERA_DISTANCE_END = DEFAULT_ROOM_HEIGHT

DEFAULT_CAMERA_ROTATION_X_ANGLE_STEP = 10.0  # degrees
MIN_CAMERA_ROTATION_X_ANGLE_STEP = 0.1
MAX_CAMERA_ROTATION_X_ANGLE_STEP = 10

DEFAULT_CAMERA_ROTATION_X_ANGLE_START = MIN_CAMERA_ROTATION_X_ANGLE  # degrees
MIN_CAMERA_ROTATION_X_ANGLE_START = MIN_CAMERA_ROTATION_X_ANGLE
MAX_CAMERA_ROTATION_X_ANGLE_START = MAX_CAMERA_ROTATION_X_ANGLE

DEFAULT_CAMERA_ROTATION_X_ANGLE_END = MAX_CAMERA_ROTATION_X_ANGLE  # degrees
MIN_CAMERA_HORIZONTAL_ROTATION_ANGLE_END = MIN_CAMERA_ROTATION_X_ANGLE
MAX_CAMERA_HORIZONTAL_ROTATION_ANGLE_END = MAX_CAMERA_ROTATION_X_ANGLE

DEFAULT_CAMERA_ROTATION_Z_ANGLE_STEP = 10.0  # degrees
MIN_CAMERA_ROTATION_Z_ANGLE_STEP = 0.1
MAX_CAMERA_ROTATION_Z_ANGLE_STEP = 10

DEFAULT_CAMERA_ROTATION_Z_ANGLE_START = -180.0  # degrees
MIN_CAMERA_ROTATION_Z_ANGLE_START = MIN_CAMERA_ROTATION_Z_ANGLE
MAX_CAMERA_ROTATION_Z_ANGLE_START = MAX_CAMERA_ROTATION_Z_ANGLE

DEFAULT_CAMERA_ROTATION_Z_ANGLE_END = MAX_CAMERA_ROTATION_Z_ANGLE  # degrees
MIN_CAMERA_ROTATION_Z_ANGLE_END = MIN_CAMERA_ROTATION_Z_ANGLE
MAX_CAMERA_ROTATION_Z_ANGLE_END = MAX_CAMERA_ROTATION_Z_ANGLE

FILE_PREFIX = "FILE_PREFIX"
DEFAULT_FILE_PREFIX = ""
DEFAULT_RENDER_SCENE_OUTPUT_PATH = f"{expanduser('~')}/Desktop/"
DEFAULT_RENDER_CAMERA_MOVEMENT_OUTPUT_PATH = f"{expanduser('~')}/Desktop/renders/"
DEFAULT_RENDER_CAMERA_FOV_CORNERS_OUTPUT_PATH = f"{expanduser('~')}/Desktop/renders/"

CAMERA_MOVEMENT_FOV_SCAN_LOCATION_KEY = "location"
CAMERA_MOVEMENT_FOV_SCAN_FILE_NAME_KEY = "file_name"
CAMERA_MOVEMENT_FOV_GRID_COORDINATES = "camera_movement_fov_grid_coordinates"
CAMERA_MOVEMENT_BEACON_DISTANCE = "camera_movement_beacon_distance"
CAMERA_MOVEMENT_ROTATION_X_ANGLE = "camera_movement_rotation_x_angle"
CAMERA_MOVEMENT_ROTATION_Z_ANGLE = "camera_movement_rotation_z_angle"

# Settings
DEFAULT_SETTINGS_PATH = f"{expanduser('~')}/Desktop/"

SETTINGS_VERSION_KEY = "version"

SETTINGS_DATE_KEY = "date"

SETTINGS_SCENE_KEY = "scene"
SETTINGS_SCENE_TILE_SIDE_KEY = "tile_side"
SETTINGS_SCENE_FLOOR_SIDE_TILES_KEY = "floor_side_tiles"

SETTINGS_ROOM_KEY = "room"
SETTINGS_ROOM_NAME_KEY = "name"
SETTINGS_ROOM_WIDTH_KEY = "width"
SETTINGS_ROOM_DEPTH_KEY = "depth"
SETTINGS_ROOM_HEIGHT_KEY = "height"
SETTINGS_ROOM_THICKNESS_KEY = "thickness"

SETTINGS_BEACON_KEY = "beacon"
SETTINGS_BEACON_NAME_KEY = "name"
SETTINGS_BEACON_WIDTH_KEY = "width"
SETTINGS_BEACON_HEIGHT_KEY = "height"

SETTINGS_CAMERA_KEY = "camera"
SETTINGS_CAMERA_NAME_KEY = "name"
SETTINGS_CAMERA_MAKE_KEY = "make"
SETTINGS_CAMERA_MODEL_KEY = "model"
SETTINGS_CAMERA_ORIENTATION_KEY = "orientation"
SETTINGS_CAMERA_FACING_KEY = "facing"
SETTINGS_CAMERA_RESOLUTION_WIDTH_KEY = "resolution_width"
SETTINGS_CAMERA_RESOLUTION_HEIGHT_KEY = "resolution_height"
SETTINGS_CAMERA_FOCAL_LENGTH_KEY = "focal_length"
SETTINGS_CAMERA_PIXEL_SIZE_KEY = "pixel_size"
SETTINGS_CAMERA_GRID_X_KEY = "grid_x"
SETTINGS_CAMERA_GRID_Y_KEY = "grid_y"
SETTINGS_CAMERA_BEACON_DISTANCE_KEY = "beacon_distance"
SETTINGS_CAMERA_ROTATION_X_ANGLE_KEY = "rotation_x_angle"
SETTINGS_CAMERA_ROTATION_Z_ANGLE_KEY = "rotation_z_angle"
SETTINGS_CAMERA_SHOW_FOW_KEY = "show_fov"

SETTINGS_CAMERA_MOVEMENT_KEY = "camera_movement"
SETTINGS_CAMERA_MOVEMENT_FOV_SCAN_ENABLED_KEY = "camera_movement_fov_scan_enabled"
SETTINGS_CAMERA_MOVEMENT_BEACON_DISTANCE_ENABLED_KEY = "camera_movement_beacon_distance_enabled"
SETTINGS_CAMERA_MOVEMENT_HORIZONTAL_ROTATION_ANGLE_ENABLED_KEY = "camera_movement_rotation_z_angle_enabled"
SETTINGS_CAMERA_MOVEMENT_VERTICAL_ROTATION_ANGLE_ENABLED_KEY = "camera_movement_rotation_x_angle_enabled"
SETTINGS_CAMERA_MOVEMENT_OUTPUT_PATH_KEY = "output_path"
SETTINGS_CAMERA_MOVEMENT_FILE_PREFIX_KEY = "file_prefix"

SETTINGS_CAMERA_MOVEMENT_DISTANCE_KEY = "distance"
SETTINGS_CAMERA_MOVEMENT_DISTANCE_START_KEY = "camera_beacon_distance_start"
SETTINGS_CAMERA_MOVEMENT_DISTANCE_END_KEY = "camera_beacon_distance_end"
SETTINGS_CAMERA_MOVEMENT_DISTANCE_STEP_KEY = "camera_beacon_distance_step"

SETTINGS_CAMERA_MOVEMENT_HORIZONTAL_ROTATION_KEY = "horizontal_rotation"
SETTINGS_CAMERA_MOVEMENT_HORIZONTAL_ROTATION_START_KEY = "camera_rotation_x_angle_start"
SETTINGS_CAMERA_MOVEMENT_HORIZONTAL_ROTATION_END_KEY = "camera_rotation_x_angle_end"
SETTINGS_CAMERA_MOVEMENT_HORIZONTAL_ROTATION_STEP_KEY = "camera_rotation_x_angle_step"

SETTINGS_CAMERA_MOVEMENT_VERTICAL_ROTATION_KEY = "vertical_rotation"
SETTINGS_CAMERA_MOVEMENT_VERTICAL_ROTATION_START_KEY = "camera_rotation_z_angle_start"
SETTINGS_CAMERA_MOVEMENT_VERTICAL_ROTATION_END_KEY = "camera_rotation_z_angle_end"
SETTINGS_CAMERA_MOVEMENT_VERTICAL_ROTATION_STEP_KEY = "camera_rotation_z_angle_step"
