# Scene

TILE_SIDE = 0.05  # meters
FLOOR_SIDE_TILES = 32  # tiles
LED_PANEL_WIDTH = 0.173  # meters

# Smartphone


FRONT_CAMERA_SENSOR_WIDTH_PX = 3880  # pixels
FRONT_CAMERA_SENSOR_HEIGHT_PX = 5184  # pixels
FRONT_CAMERA_FOCAL_LENGTH_MM = 3.52  # millimetres
FRONT_CAMERA_PIXEL_SIZE_UM = 0.9  # micrometres

BACK_CAMERA_SENSOR_WIDTH_PX = 3024  # pixels
BACK_CAMERA_SENSOR_HEIGHT_PX = 4032  # pixels
BACK_CAMERA_FOCAL_LENGTH_MM = 4.216  # millimetres
BACK_CAMERA_PIXEL_SIZE_UM = 1.4  # micrometres

# Analysis

RESULTS_FOLDER = "results"
DEBUG_FOLDER = "debug"
DATA_FILENAME_PREFIX = "data"
DATA_FILENAME_SUFFIX = "csv"
INDEX_OUT_OF_RANGE = -1
IMAGE_PATH = "Image Path"
X = "X"
Y = "Y"
ESTIMATED_X = "Estimated X"
ESTIMATED_Y = "Estimated Y"
PLOT_WIDTH = 1280
PLOT_HEIGHT = 960
PLOT_DPI = 100

PYPLOT_SIZE = 15
PYPLOT_LEGEND_FONT_SIZE = "large"
PYPLOT_FIGURE_SIZE = (20, 8)
PYPLOT_AXES_LABEL_SIZE = PYPLOT_SIZE
PYPLOT_AXES_TITLE_SIZE = PYPLOT_SIZE
PYPLOT_XTICK_LABEL_SIZE = PYPLOT_SIZE * 0.85
PYPLOT_YTICK_LABEL_SIZE = PYPLOT_SIZE * 0.85
PYPLOT_AXES_TITLE_PAD = 25

DEBUG_DATA_FILE_MAIN_SECTION = "DATA"
DEBUG_DATA_IMAGE_PATH_KEY = "image_path"
DEBUG_DATA_IMAGE_CENTER = "image_center"

# Exif

EXIF_LOCATION = "location"
EXIF_LOCATION_X = "x"
EXIF_LOCATION_Y = "y"
DECIMAL_PRECISION = 4
